name: Spider

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 0"
  
jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install
      - name: Spider
        run: npm run spider

      - uses: EndBug/add-and-commit@v7
        with:
          message: 'fix: spider new books'